{%set name = "fuzzywuzzy" %}
{%set version = "0.12.0" %}
{%set hash_type = "sha256" %}
{%set hash_val = "0a39865799ada1d514c8ac612194a2d1c8a335f67c17078d5ab0bb9ec980ac33" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash_val }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-levenshtein

test:
  imports:
    - fuzzywuzzy
    - fuzzywuzzy.StringMatcher
    - fuzzywuzzy.fuzz
    - fuzzywuzzy.process
    - fuzzywuzzy.string_processing
    - fuzzywuzzy.utils

about:
  home: https://github.com/seatgeek/fuzzywuzzy
  license: MIT
  summary: 'Fuzzy string matching in python'

extra:
  recipe-maintainers:
    - pmlandwehr
    - josegonzalez
