travis:
  secure:
    BINSTAR_TOKEN: kArzuLSdCAfhZgqfecaRN5jYCqnHJZcMVLyOwNCwBUa+nPQRZdOOZJ80+/3MzD9bgbplLEAdX9A220FFrIFiCgl0uQeNiPXC9MQZUi7u2IWD7X0xKJH5KuyFX+uAAoDsl3SptrfIBFLPU/W3RpS1rOhQK3ZRZCWVODBZ6uUFIdfsed3Vr7JtrNV75E8WHRPiJLK2XCfQDuI7Iy8Y3oNFjtPYThVx8g4MHGsVT/M2hv5VlgxyypmYCv5bO4SSMfiG8cCFZQMeiJb05KebMFt0VTJw5g44RxDpcgxCB4hrjzPVRPaWq0YyTR4kmVU1+WCXapZokBwjMgcCDnOwbWCsKQbR3Q3AQmACrgjca1FvfxgqTaBurCEksxaOM4b7lgLVry32ipteXUBUFRSYABanVVCkjAyrApo2hP9naVUnXG/1VmDmPycnxTpuUg2xez4wVCJznEXYiF8o5ch/L6IRM2ib0jDSenoi/y7FDGkmpEcV30GX0iCwBSGomztk3ZCCZN/p5sAGFF6YLDmDnLVK7Q49p3VTLeG+XtIUboAqoH5BicFzsmlyxtk+RbGCwyiI+gfyRTVM8IqMM+Cof+32FtKsQxWx8v85RkjqGmLRtvAdPzjoCWNZgyGlkxHh80URiaMFUhd363SUa1NJD/RRSkHzjr/PW0RgIDPFEW9ZrpY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
