travis:
  secure:
    BINSTAR_TOKEN: O+lQvy+r5lZOZxBpOsf4O6tCEHjK12tMrFg2BZVOLlujMGa5PcOPMMNDcsmMnQeu3dvVm8MU6BEUEOhiA2b0POOSYTS2vvEksOSko856jucyq4KixdcOOruIqXW6YP544AQLUjjPrToG5MZcwpWBxkT0AUkGMoMVrFedZWKppiw0+Y1YFJOdNRcPqwm3l9TkUZAuYdKcMiUidqrBOSOT/qiKYh/+tU1TCAiuErzH+hse9/IeVLx/vrDuFYBMEqOm2gezg+3cXJeMkT3eAKH7Pr8OZcTFztTp48pyhxiElQdk3mN0Sc66ECf5mi2MUzziAz9ONJ8HJZ8u7JqGEgTamvFA1czBpSLfG3jsRuumbEI45CaIgCW0l3cX+BW1LWUieiES/Sua5aHw/4DXUZYEcun5MsE1iFmNWS5u0oPQ2+/wYUHEQPg6nqipN/56bmIg7/U5NnWhHYc3DxMOpOoalL43pFDl2hSl+saQ4Db2sWxUKBa+bVYWdw7UwtaSGEgXsOcKrrLZLj5hapgq05mATmcsqRF6sWdviiy4UIiBdiYyC5DrjEAyWgQ9uXFfCAK94IT+RNqw3xFr09+v85DjbhCup8rLs6tYxmjwLr3KIVAhAXn5H93Cuu30HgHuaVBV434Z9sKFjDj0cZoHHHwsvxHifpkhqyr1Ac1HySc6DKg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
